export const UtxoTxDetailsLabelsToKeep = [
  'Txid',
  'From',
  'To',
  'Block Hash',
  'Confirmations',
  'Block Time',
  'Fees',
];

export const EvmTxDetailsLabelsToKeep = [
  'Hash',
  'From',
  'To',
  'Block Hash',
  'Confirmations',
  'Timestamp',
  'Max Fee Per Gas',
  'Nonce',
  'Gas Used',
  'Gas Price',
  'Success',
  'Revert Reason',
  'Method',
];

export const EnhancedEvmTxDetailsLabelsToKeep = [
  'Hash',
  'From',
  'To',
  'Value',
  'Block Number',
  'Block Hash',
  'Confirmations',
  'Timestamp',
  'Gas Limit',
  'Gas Price',
  'Gas Used',
  'Max Fee Per Gas',
  'Max Priority Fee Per Gas',
  'Nonce',
  'Success',
  'Revert Reason',
  'Method',
  'Input',
];
