#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm if it exists
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use npx to run the local tsc
npx tsc --pretty --noEmit