#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm if it exists
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Now yarn should be able to find node
yarn lint-staged
