#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load nvm if it exists
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use the type-check script from package.json
yarn type-check